<?php
/**
* Studio Alice, 2014, studioalice.se, magnus@studioalice.se
* Template for footer
*
* @category    design
* @package     rwd_default
* @copyright   Copyright (c) 2014 Studio Alice AB. (http://studioalice.se)
 */
?>

<!-- <footer class="footer" role="contentinfo">
  <?php echo $this->getChildHtml() ?>
  <address><?php echo $this->getCopyright() ?></address>
</footer> -->


<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml() ?>
        <p class="bugs"><?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a href="http://www.magentocommerce.com/bug-tracking" onclick="this.target='_blank'"><strong><?php echo $this->__('Report All Bugs') ?></strong></a> <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?></p>
        <address><?php echo $this->getCopyright() ?></address>
    </div>
</div>
