<?php
/**
 * Studio Alice, 2014, studioalice.se, magnus@studioalice.se
 *
 * @category    design
 * @package     rwd
 * @copyright   Copyright (c) 2014 Studio Alice AB
 * @license
 */

?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove Item') ?>"
    class="secondary-button btn-remove btn-remove2"><?php echo $this->__('Remove item');?></a>
