<?php
/**
* Studio Alice, 2014, studioalice.se, magnus@studioalice.se
* Template for footer
*
* @category    design
* @package     rwd_default
* @copyright   Copyright (c) 2014 Studio Alice AB. (http://studioalice.se)
 */
?>

<footer class="footer clear" role="contentinfo">
<div class="signup-link">
    <?php echo $this->getChildHtml('footer.newsletter') ?>
</div>

<div class="service-links">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
</div>
<div class="payment-icons">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_payment')->toHtml() ?>
</div>
<div class="search-links">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_site')->toHtml() ?>
</div>
  <address class="copyright"><?php echo $this->getCopyright() ?></address>
  <address class="theme-created">Theme created by <a href="studioalice.se">Studio Alice AB</a></address>
</footer>
