<?php
/**
 * Studio Alice, 2014, studioalice.se, magnus@studioalice.se
 *
 * @category    design
 * @package     rwd
 * @copyright   Copyright (c) 2014 Studio Alice AB
 * @license
 */

/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<aside class="add-info">
  <?php if($_additional = $this->getAdditionalData()): ?>
    <h2><?php echo $this->__('Additional Information') ?></h2>
    <dl>
      <?php foreach ($_additional as $_data): ?>
    	<dt><?php echo $this->escapeHtml($this->__($_data['label'])) ?></dt>
    	<dd><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></dd>
    	<?php endforeach; ?>
    </dl>
    <!--
<table class="data-table" id="product-attribute-specs-table">
      <col width="35%" />
      <col />
      <tbody>
        <?php foreach ($_additional as $_data): ?>
          <tr>
            <th class="label"><?php echo $this->escapeHtml($this->__($_data['label'])) ?></th>
            <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
-->
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
  <?php endif;?>
</aside>

<div class="buybutton-mobile">
    <?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
  </div>
