<?php
/**
 * Studio Alice, 2014, studioalice.se, magnus@studioalice.se
 *
 * @category    design
 * @package     rwd
 * @copyright   Copyright (c) 2014 Studio Alice AB
 * @license
 */
?>
<?php
    $columns = $this->getColumns();
?>
<section class="wishlist clear">
  <!-- <div class="wish-headlines">
    <?php foreach ($columns as $column): ?>
        <h4><?php echo $column->getTitle();?></h4>
    <?php endforeach; ?>
  </div> -->
  <div class="wishlist-items" id="wishlist-table">
    <?php if (count($this->getItems())): ?>
        <?php foreach ($this->getItems() as $item): ?>
            <ul id="item_<?php echo $item->getId();?>">
                <?php foreach ($columns as $column): ?>
                    <li><?php $column->setItem($item); echo $column->toHtml($item);?></li>
                <?php endforeach; ?>
            </ul>
        <?php endforeach ?>
    <?php else: ?>
        <h3 class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></h3>
    <?php endif; ?>
  </div>
</section>

<!-- <table class="data-table" id="wishlist-table">
    <thead>
        <tr>
            <?php foreach ($columns as $column): ?>
                <th><?php echo $column->getTitle();?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->getItems())): ?>
            <?php foreach ($this->getItems() as $item): ?>
                <tr id="item_<?php echo $item->getId();?>">
                    <?php foreach ($columns as $column): ?>
                        <td><?php $column->setItem($item); echo $column->toHtml($item);?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <td colspan="<?php echo count($columns);?>" class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></td>
        <?php endif; ?>
    </tbody>
</table> -->
<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('wishlist-table');

<?php foreach ($columns as $column): ?>
    <?php echo $column->getJs();?>
<?php endforeach; ?>
//]]>
</script>
