<?php
/**
* Studio Alice, 2014, studioalice.se, magnus@studioalice.se
* Template for basic page
*
* @category    design
* @package     rwd_default
* @copyright   Copyright (c) 2014 Studio Alice AB. (http://studioalice.se)
*
* Template for Mage_Page_Block_Html
*/
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
  <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<header class="header clear" role="banner">
  <?php echo $this->getChildHtml('header') ?>
</header>
<div class="wrapper clear">
  <aside class="sidebar" role="complementary">
    <?php echo $this->getChildHtml('left') ?>
    <!-- <div class="menubutton" id="menubutton">MENY &#9660;</div> -->
    <nav class="nav clear menu" role="navigation" id="navmenu">

    </nav>
    
    <div class="recent">
      <?php echo $this->getChildHtml('right') ?>
    </div>

  </aside>

  <main class="main clear" role="main">

    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <article>
      <?php echo $this->getChildHtml('global_messages') ?>
      <?php echo $this->getChildHtml('content') ?>
    </article>
  </main>
  
</div>
<footer class="footer clear" role="contentinfo">
  <div class="subsrcibe-link">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
      <label for="newsletter"><?php echo $this->__('Sign up for our newsletter') ?></label>
      <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
      <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><?php echo $this->__('Subscribe') ?></span></button>
    </form>
    <script type="text/javascript">
//<![CDATA[
var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>
</div>
<div class="service-links">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
</div>
<div class="payment-icons">
  <p>Payment</p>
</div>
<div class="search-links">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_site')->toHtml() ?>
</div>

<?php //echo $this->getChildHtml('footer') ?>

<address><?php echo $this->getCopyright() ?></address>

<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
</footer>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
