<?php
/**
* Studio Alice, 2014, studioalice.se, magnus@studioalice.se
* Proceed button on checkout page
 *
 * @category    design
* @package     rwd_default
* @copyright   Copyright (c) 2014 Studio Alice AB. (http://studioalice.se)
 */
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
    <dl class="grandtotal">
        <dt><strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></dt>
        <dd><strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong></dd>

        <dt><strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong></dt>
        <dd><strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong></dd>
    </dl>
<!-- <tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr> -->
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<!-- <tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr> -->
<?php else:?>
    <dl class="grandtotal">
        <dt><strong><?php echo $this->getTotal()->getTitle() ?></strong></dt>
        <dd><strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong></dd>
    </dl>
<!-- <tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr> -->
<?php endif;?>
