<?php
/**
 * Studio Alice, 2014, studioalice.se, magnus@studioalice.se
 *
 * @category    design
 * @package     rwd
 * @copyright   Copyright (c) 2013 Studio Alice AB.
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="recent">
    <div class="block-title">
        <h4><?php echo $this->__('Recently Viewed Products') ?><h4>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<?php endif; ?>
