<?php
/**
 * Studio Alice, 2014, studioalice.se, magnus@studioalice.se
 *
 * @category    design
 * @package     rwd
 * @copyright   Copyright (c) 2014 Studio Alice AB
 * @license
 */

/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<aside class="add-info">
  <?php if($_additional = $this->getAdditionalData()): ?>
    <h2><?php echo $this->__('Additional Information') ?></h2>
    <dl>
      <?php foreach ($_additional as $_data): ?>
    	<dt><?php echo $this->escapeHtml($this->__($_data['label'])) ?></dt>
    	<dd><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></dd>
    	<?php endforeach; ?>
    </dl>

    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
  <?php endif;?>
</aside>
