<?php
/**
* Studio Alice, 2014, studioalice.se, magnus@studioalice.se
* Template for crossell (checkout page)
*
* @category    design
* @package     rwd_default
* @copyright   Copyright (c) 2014 Studio Alice AB. (http://studioalice.se)
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
  <div class="crosssell">
    <h4><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h4>
    <ul id="crosssell-products-list">
      <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
          <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
          <div class="product-details">
            <h4 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h4>
            <?php echo $this->getPriceHtml($_item, true) ?>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>

            <p class="add-to-links"><?php if ($this->helper('wishlist')->isAllow()) : ?>
             <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
           <?php endif; ?></p>

           <p class="add-to-links"><?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
              <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
          <?php endif; ?></p>

                <!-- <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                  </ul> -->
                </div>
              </li>
            <?php endforeach; ?>
          </ul>
          <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
        </div>
      <?php endif; ?>
