<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    
    <link href="style.css" rel="stylesheet" type="text/css">
    
</head>
<body>
    <header class="header clear" role="banner">
      <?php echo $this->getChildHtml('header') ?>
    </header>
    <div class="wrapper clear">
      <aside class="sidebar" role="complementary">
        <?php echo $this->getChildHtml('left') ?>
        <div class="logo">
          
        </div>
        <div class="menubutton" id="menubutton">MENY &#9660;</div>
          <nav class="nav clear menu" role="navigation" id="navmenu">
            
          </nav>
          <div class="layernav">
            
          </div>
          <div class="recent">
            
          </div>
          
        </aside>
    
        <main class="main" role="main">
          <div class="content">
            <?php echo $this->getChildHtml('content') ?>
            
            <article>
              
            </article>
          </div>
        </main>
      </div>
    
    <footer class="footer" role="contentinfo">
      <?php $this->getChildHtml('footer') ?>
    </footer>
</body>
</html>
